# Generated by Django 6.0.6 on 2026-06-08 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('stipend', models.CharField(blank=True, default='', max_length=100)),
                ('eligibility', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institute', models.CharField(max_length=200)),
                ('programme', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(max_length=20)),
                ('motivation', models.TextField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('email_sent', 'Email Sent'), ('anumati_invited', 'Anumati Invited'), ('documents_received', 'Documents Received'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('anumati_invited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.position')),
            ],
        ),
    ]
