# Generated by Django 6.0.6 on 2026-07-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='application',
            name='cgpa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('In-person', 'In-person'), ('Hybrid', 'Hybrid')], default='Remote', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_faculty',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='requested_duration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='requested_duration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
